modLoader="javafml" #mandatory
loaderVersion="[35,)"
license="All rights reserved"
issueTrackerURL="https://github.com/zOnlyKroks/Hardcore-Extended/issues" #optional

[[mods]] #mandatory
modId="hardcoreex" #mandatory
version="0.7" #mandatory
displayName="Hardcore Extended" #mandatory
#updateJSONURL="http://myurl.me/" #optional | This won't work as the url is invalid.
displayURL="https://www.curseforge.com/minecraft/mc-mods/hardcore-extended" #optional
logoFile="logo.png" #optional
credits="To all my suporters" #optional
authors="zOnlyKroks" #optional
description='''
A Mod wich automates the No Damage Challange
'''

[[dependencies.hardcoreex]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[35,)" #mandatory
    ordering="NONE"
    side="CLIENT"

[[dependencies.hardcoreex]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,1.17)"
    ordering="NONE"
    side="BOTH"
